version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

  frontend:
    build:
      context: ./static
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html
